### PR TITLE
Update readme to be about Kite

### PR DESCRIPTION
**Pull request by plungg**
Updated to be similar to [Atom plugin's readme](https://github.com/kiteco/atom-plugin/blob/master/README.md).

### Work to be done:

- [x] Add min. JLab version
- [x] Confirm: Will extension manager be enabled by default when this release is out?
- [x] Troubleshooting steps for manual installation → what command to run
- [x] Change section header to "completion documentation"
- [x] Switch screenshots to the ones hosted in this repo

Add updated screenshots for:
- [x] Tutorial 
- [x] Autocompletions
- [x] Function documentation
- [x] Command Palette

### CODE REVIEW

**Comment by plungg** [comment]
@edzkite @ryantberg 
- What is the min JLab version? Will it be `2.1.5`? The last release in [their changelog](https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#changelog) was `2.1.4` so I'm assuming your latest core changes will be in by that release.
- Can you confirm that the extension manager will be enabled by default when this release is out? [The JLab demo from their Github](https://github.com/jupyterlab/jupyterlab-demo) does not have a `beta` badge, whereas the old dev build setup steps does.
- Can you provide the manual installation steps if the extension isn't automatically detected?

**Comment by edzkite** [comment]
The min version would be 2.2.0

**Comment by edzkite** [comment]
> * Can you confirm that the extension manager will be enabled by default when this release is out? [The JLab demo from their Github](https://github.com/jupyterlab/jupyterlab-demo) does not have a `beta` badge, whereas the old dev build setup steps does.

Sure. Since the old dev build though, I believe the UI is enabled by default.

> * Can you provide the manual installation steps if the extension isn't automatically detected?

`pip install jupyter-kite` and
`jupyter labextension install @kiteco/jupyterlab-kite `

**Comment by plungg** [comment]
> > * Can you provide the manual installation steps if the extension isn't automatically detected?
> 
> `pip install jupyter-kite` and
> `jupyter labextension install @kiteco/jupyterlab-kite `

This is about manually installing the plugin but what about the cases where both the plugin and Kite engine are installed, but the engine cannot locate the plugin? Eg. user runs JLab in a virtual environment @ryantberg

**Comment by ryantberg** [comment]
> Ah, let me clarify, what about cases where the plugin is installed but not detected by the Kite engine? Eg. user runs JLab in a virtual environment @ryantberg

Is the goal to make the Kite Plugin Manager aware of the undetected plugin installation? That's not necessary for use of the plugin--it only affects plugin manager UX. If we think that's important then we're going to need to revisit non-conda JL installations in the plugin manager, which we had previously decided to table.

For installing the plugin, the user also needs to have nodejs installed, so that should be listed as an installation step. We have time slotted to investigate this dependency, so if we remove it we can always take the step out later. From jupyterlab-lsp:


> 4. install nodejs
```
conda install -c conda-forge nodejs
# or one of the following, as an administrator
choco install nodejs            # Windows with Chocolatey
sudo apt-get install nodejs     # Debian/Ubuntu
sudo brew install nodejs        # MacOS with Homebrew
sudo dnf install nodejs         # Fedora
sudo yum install nodejs         # RHEL/CentOS
```

**Comment by plungg** [comment]
@ryantberg Got it. If the plugin can be used without it being detected in the plugin manager UX, that's fine. I'll mention in support articles that if the plugin manager doesn't detect the JLab extension:
* Kite should still work
* Uninstall is only via the JLab extension manager.

Will add the `nodejs` part. Thanks!

**Pull request merged**
