### PR TITLE
Add screenshots and test data

### PR DESCRIPTION
**Pull request by plungg**
### To finish
- [x] Add rest of screenshots
- [x] Confirm screenshots are correct size

### CODE REVIEW

**Comment by plungg** [comment]
@edzkite @ryantberg Look this over and see if everything is fine? Also, if the folder location is OK.

I added media and CSV files, which finishes the onboarding file and has all media except for a command palette screenshot for the readme.

**Comment by ryantberg** [comment]
I think we may need to move this folder into `packages/jupyterlab-kite` if we want these assets to be available in the plugin.

Is there supposed to be a notebook in this PR or is that coming separately?

**Comment by plungg** [comment]
@ryantberg actually, this doesn't make sense to be included in the package itself. I just need a place to host these images and test files - the notebook will access them via URL. I'll reach out to the marketing team to get it hosted on the website

**Comment by ryantberg** [comment]
Ah okay, that location seems fine then.

**Pull request closed without merging**
